spring.application.name=Backend
server.port=3979

spring.datasource.url=jdbc:mysql://localhost:3306/swp391
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# = JPA / Hibernate Configuration
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

#google login config
spring.security.oauth2.client.registration.google.client-id=289373167901-8cl451pehm1daalvl1hhitkqc9t625s1.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:3979/login/oauth2/code/google
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://openidconnect.googleapis.com/v1/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=email
#config GEMINI AI
spring.ai.openai.api-key=AIzaSyC5tCE7Z08wHRj_Em2UkKds6E5sbYAfZYY
spring.ai.openai.chat.base-url=https://generativelanguage.googleapis.com
spring.ai.openai.chat.completions-path=/v1beta/openai/chat/completions
spring.ai.openai.chat.options.model=gemini-1.5-flash

#cloudinary config
cloudinary.cloud_name=dnjykfio6
cloudinary.api_key=397833716479588
cloudinary.api_secret=8Hvyo0E_59XXY4UN7euvn71i00Y

#jwt config
jwt.secret=CqXeW3kjj94zddRR+nWPGDkY1pU6c1YUXjgYcE5SyAj/SzwPGhqbzExoPg06qMeC
jwt.expiration= 15 
refreshjwt.expriation= 2 

#Admin config
#admin.username=admin
#admin.password=Admin@123
#admin.email=admin20@gmail.com

#mail config


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=magicmath2k5@gmail.com
spring.mail.password=otkbbsemdoisfqzd
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
